DROP TABLE IF EXISTS tbl_textos;

CREATE TABLE tbl_textos (
    id int(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
    id_seccion int(11) NOT NULL,
    paginaPadre varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_spanish_ci NOT NULL,
    identificacion varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_spanish_ci NULL,
    texto mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_spanish_ci NOT NULL,
    INDEX fk_tbl_textos_tbl_secciones (id_seccion),
    CONSTRAINT fk_tbl_textos_tbl_secciones FOREIGN KEY (id_seccion) REFERENCES tbl_secciones (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_spanish_ci;

INSERT INTO tbl_textos (id_seccion, paginaPadre, identificacion, texto ) VALUES 
(21, 'historia', 'Foundation', 'UNICAB Educational Corporation was created in the city of Sogamoso by Resolution No. 0194 of July 18, 2001, issued by the Government of Boyacá. From its inception, it was established as a non-profit institution, with a philosophy focused on offering the right to education in an innovative manner, tailored to the needs of those involved in its processes, fostering the exchange of knowledge and strengthening the leadership of its participants. <br> <br> From its creation until 2007, UNICAB Educational Corporation developed various services:' ),
(21, 'historia', '2002-2003', '<b>With the Sogamoso Chamber of Commerce:</b> training, capacity building and empowerment processes were carried out for merchants in Sogamoso and in eight municipalities of the Sugamuxi Province, through strategies focused on marketing, sales and customer service, among others. <br> <br> <b>Project “Recovery of the Social Fabric of the Coal Production Chain of the Cundiboyacense Highlands”:</b> This project, led by the United Nations Development Programme (UNDP), was implemented in 13 coal-producing municipalities in Boyacá. Training, awareness-raising, and capacity-building processes were carried out for mine workers, their families, and communities.' ),
(21, 'historia', '2004-2007', '<b>With the Colombian Institute of Family Welfare (ICBF) and municipalities in the provinces of Sugamuxi and Tundama:</b> In Sugamuxi: Sogamoso, Duitama, Paipa, Iza, Monguí, Gámeza, Mongua, Aquitania, Tota, Cuítiva, Corrales. In Tundama: Paipa, Duitama, Sogamoso, Corrales, Nobsa. The following took place: <b>The Family Educator program.</b> <br> <br> <b>Program for Attention to Dispersed Rural Populations and The Family Educator:</b> Co-financed by the ICBF and 10 municipalities in the provinces of Tundama and Sugamuxi, this program served rural communities and populations with specific educational needs. <br> <br>In 2007, the need arose to serve people with special socioeconomic conditions, such as high-performance athletes, artists, families in constant global mobility, and farmers who could not access face-to-face education.' ),
(21, 'historia', '2007-2008', 'To address this need, a provisional operating license to provide educational services using ICT was requested from the Sogamoso Education Secretariat. Thus, the <b>UNICAB Virtual College project </b>(www.unicab.org), authorized by Resolution No. 061 of December 15, 2007. <br> <br> Since 2008, the UNICAB Virtual School has graduated 655 eleventh-grade students and served over 5,000 students, including athletes, artists, children, teenagers, and adults. This model has enabled students to achieve outstanding academic results, fostering skills and motivating them to reach their goals. Many have earned scholarships to national and international universities.' ),
(23, 'historia', 'giu', 'It is a collegial research body comprised of a group of professors and external advisors, whose objective is to advance scientific, technological, pedagogical, and complementary strategic developments within the UNICAB Ecosystem pedagogical model. This group manages coherent research projects and proposals aimed at consolidating cognitive, propaedeutic, strategic, methodological, and synergistic components to develop learning content, sequences, and methods. All of this is applied to online education in a disruptive and innovative way within a cyber environment, formulating and responding with rigorous research to one or more problems in the field. Furthermore, it provides solutions and corrective measures through medium- and long-term strategic plans, in order to generate concrete knowledge on the topics addressed.' ),
(23, 'historia', 'creative', 'It is comprised of a select group of faculty members from the institution and external consultants who freely and voluntarily contribute their intellect and creativity to the instructional, visual, corporate, pedagogical, and advertising development. This team is responsible for reviewing and monitoring the teaching and learning materials produced by the faculty members before they are published on technological platforms and communication channels. It also contributes to academic management, business planning, inter-institutional events, and required advertising work.' ),
(23, 'historia', 'systems', 'It is comprised of faculty members, external systems engineers, and partners who freely and voluntarily contribute to the holistic and technological development of the institution. This team organizes and maintains the necessary hardware resources for software execution, always striving for maximum speed and quality in the management of institutional information. It coordinates actions with the various departments and system users to ensure excellent quality in the school´s IT processes. Furthermore, it performs updates, support, and technical maintenance, adhering to current standards and procedures. It provides hardware and software technical support, trains users on program usage, installs and updates applications required for the platforms, and conducts periodic checks. It also assists in understanding and using the implemented technologies, monitoring their application and operation.' ),
(23, 'historia', 'style', 'This team is responsible for reviewing the content generated by teachers on the platform, ensuring its quality and accuracy. They receive access to the content from the thought leader and provide feedback through reports that include observations and suggestions for improvement. They also review documents before publication or distribution through various communication channels. Like the creative team, they may use a checklist format to guarantee a structured and efficient analysis.' ),
(23, 'historia', 'teachers', 'This group comprises all teaching staff with academic responsibilities at the UNICAB Virtual College who are also assigned the role of degree program director. This year, a form called the General Degree Program Director´s Report was implemented to document both the academic workload and the activities related to degree program directorship. While we have complete confidence in the staff´s work, experience has shown the importance of documenting the actions taken. <br><br> The group also assesses students level of engagement in critical thinking, describing each student´s performance to establish objective evaluation criteria. This allows for the implementation of preventative, corrective, and productive strategies to improve performance and ensure students inclusion or advancement.' ),

(29, 'principiosYValores', 'Commitment', 'The school is committed to developing, through continuous improvement and the efforts of a team of workers who study, research, attend to and provide the best educational services to the community, guaranteeing the quality and excellence of learning in the life projects of students who have discovered skills and abilities, and who enhance them with autonomy, freedom and identity motivated by the desire to meet their expectations, the achievement of the goals and objectives of the institution, so that they freely transform a true education that develops their personality autonomously, appropriating knowledge in their practical life as proposed by John Dewey and as a result of individual, family and community benefit.' ),
(29, 'principiosYValores', 'Honesty', 'To act responsibly and ethically in accordance with current regulations in all aspects related to the development and interaction of the institution´s activities with society. To be transparent in all matters, and to ensure that each of the policies adopted within the school, as well as the commitments made, are supported by defined, integrated processes and executed according to the proposed quality standards, through a defined structure of institutional operations and their impact on society.' ),
(29, 'principiosYValores', 'Liberty', 'It is the answer to the ideological syllogism of what is expected in relation to what one is. Our students undergo a process of accompaniment that allows them to identify and define themselves in order to be free, so that, empowered, they feel efficient when making decisions; therefore, we always seek and prioritize the truth without restrictions, to produce knowledge and the progress of society with awareness of their interests, rights, duties and political responsibilities with a high sense of collective responsibility.' ),
(29, 'principiosYValores', 'Equity', 'The pedagogical dimension of equity in education underpins its strategic approach to addressing persistent inequalities despite global policies aimed at expanding opportunities. We uphold a concept of comprehensive equity that incorporates the principles and goals of education in Colombia, along with social inclusion for participation and empowerment. This concept is grounded in critical pedagogies, capacity building, and student-centered education, encompassing inclusive and dialogical educational processes to strengthen the agency of non-traditional students within a virtual pedagogical model. This empowers them to learn and to reverse accumulated educational and social exclusions. This dimension is key to optimizing strategies for expanding accessibility and coverage, which the General Education Law so frequently addresses in light of the failures experienced by traditional students. This is evidenced in the analysis of innovative practices presented in this educational project.' ),
(29, 'principiosYValores', 'Responsibility', 'It emerges as an alternative to meet the needs of those who, being different, seek to be welcomed and supported in their extracurricular activities in the arts, sports, science, technology, and research that shape the contemporary world. These individuals, curious and committed, wish to engage with this world, but conventional educational norms often deny them the space to fulfill the dreams and aspirations that set them apart. UNICAB recognizes this need and aligns itself with the desire of those whose life projects aim to transcend to other realms. They are supported by a team of dedicated teachers who guide the teaching and learning processes with sensitivity and awareness, making them flexible through virtual platforms and humanizing the process through an eco-systemic and research-based pedagogical model.' ),

(30, 'cartiHome', 'Mission', '<b>CARTI EXPLORE</b> It is the High Performance Center for Talent and Intelligence, innovative and relevant, established as a highly humanistic center for talent development for children and young people, where formal education, culture and sport converge, with the redefinition of learning so that human beings develop their skills, abilities and talents, solve their problems equitably and expand their opportunities in pursuit of happiness.' ),
(30, 'cartiHome', 'Vision', '<b>CARTI EXPLORE</b> By 2030, it will be recognized regionally and nationally as a school established as a high-performance training center, a model in redefining educational paradigms, a leader in talent development and virtual education, consistently applying innovative approaches, inspiring the strengthening of sports, cultural, scientific, and social disciplines, fostering 21st-century skills, and celebrating creativity, research, and effort to give meaning to its students lives.' ),
(30, 'cartiHome', 'Institutional Principles', '<b>CARTI EXPLORA</b>, It promotes the comprehensive development of its students in a completely innovative context, through a physical, digital, curricular and training structure so that the learning outcome of its students is autonomous and conscious in a learning process defined with a flexible, dynamic, relevant teaching methodology based on ethical principles so that together with the development of capacities, skills and abilities in specific areas, they can have an excellent performance in their' ),
(30, 'cartiHome', 'Commitment', 'The school is committed to developing, through continuous improvement and the efforts of a team of workers who study, research, attend to, and provide the best educational services to the community, the quality and excellence of learning in the life projects of students who have discovered skills and abilities, and who enhance them with autonomy, freedom, and identity, motivated by the desire to meet their expectations, the achievement of the institution´s goals and objectives, so that they freely transform a true education that develops their personality autonomously, appropriating knowledge in their practical life as proposed by John Dewey, and as a result, individual, family, and community benefit.' ),
(30, 'cartiHome', 'Ethics', 'To act responsibly and honestly in accordance with current regulations in all aspects related to the development and interaction of the institution´s activities with society. To be transparent in all matters, and to ensure that each of the policies adopted within the school, as well as the commitments made, are supported by defined, integrated processes and executed in accordance with the proposed quality standards, through a defined structure of institutional operations and their impact on society.' ),
(30, 'cartiHome', 'Liberty', 'It is the answer to the ideological syllogism of what is expected in relation to what one is. Our students undergo a process of accompaniment that allows them to identify and define themselves in order to be free, so that, empowered, they feel efficient when making decisions; therefore, we always seek and prioritize the truth without restrictions, to produce knowledge and the progress of society with awareness of their interests, rights, duties and political responsibilities with a high sense of collective responsibility.' ),
(30, 'cartiHome', 'Equity', 'The pedagogical dimension of equity in education underpins its strategic scale for addressing the inequalities that persist despite policies aimed at expanding opportunities worldwide. We support a concept of comprehensive equity that incorporates the principles and aims of education in Colombia, along with social inclusion for participation and empowerment. This concept is grounded in critical pedagogies, capacity building, and student-centered education, encompassing inclusive and dialogical educational processes to strengthen the agency of non-traditional students within a disruptive pedagogical model. This model aims both to facilitate learning and to reverse accumulated educational and social exclusions. This dimension is key to optimizing strategies for expanding accessibility and coverage, which the General Education Law so frequently addresses in light of the failures experienced by traditional students. This is evidenced in the analysis of innovative practices present in this educational project.' ),
(30, 'cartiHome', 'Responsabilidad', 'It arises as an alternative to meet the needs of those who, being different, request to be welcomed and accompanied in their educational processes and activities to strengthen the talents associated with the arts, sports, science, technology, and research that develops the contemporary world, in which they curiously and committedly want to develop, but which, due to educational conventions, are not allowed spaces to fulfill dreams and concerns that make them different.<br><br><b>CARTI EXPLORE</b> Find that scheme and join the desire of those who, because of their life project, want to transcend to other scenarios, accompanied by a team of committed teachers who guide the teaching and learning processes with sensitivity and awareness and make them flexible through experiences of exploration and deepening of talent, humanizing the process, through an eco-systemic and investigative pedagogical model.'),
(30, 'cartiHome', 'Pertinence', 'There will be ongoing self-evaluation of the school´s potential regarding its strategies and methodologies in various areas, including intellectual, socio-emotional, and practical aspects. This involves the quality of relationships, testimonials from current and future graduates, and family participation, all aimed at cultivating a critical perspective on contemporary society. This will foster continuous redesign based on democracy and participation, promoting collaborative work among families, teachers, students, and the community. Therefore, CARTI EXPLORA, under the leadership of its directors, will consolidate educational quality and suitability through continuous pedagogical reflection, the adoption of more effective teaching methodologies and techniques, and the ongoing professional development of its staff, thus making our pedagogical model truly organic.'),

(31, 'blog', 'linkBusqueda', 'Celebration of Achievements'),
(31, 'blog', 'linkBusqueda', 'Projects and experiences'),
(31, 'blog', 'linkBusqueda', 'GIU Research'),
(31, 'blog', 'barraBusqueda', 'Search'),

(34, 'entrevista', 'Step 1.', 'Enter the following information to begin the enrollment process at our UNICAB Virtual school.'),
(34, 'entrevista', 'Step 2.', 'Additional student information.'),
(34, 'entrevista', 'Step 3.', 'Additional guardian information.');

INSERT INTO tbl_textos (id_seccion, paginaPadre, identificacion, texto ) VALUES 
(36, 'admisiones', 'Texto1', 'REGISTRATION SUCCESSFULLY COMPLETED FOR THE DOCUMENT: '),
(36, 'admisiones', 'Texto2', 'The following will be sent to the parent/guardian´s email address:'),
(36, 'admisiones', 'Texto3', 'A link to answer the admission assessment that must be submitted at the time of the interview.'),
(36, 'admisiones', 'Texto4', 'A link with the day and time the interview was scheduled.'),
(36, 'admisiones', 'Texto5', 'When you receive the email, you will likely see an image like this:'),
(36, 'admisiones', 'Texto6', 'Do not click on any of the options in the image.'),
(36, 'admisiones', 'Texto7', 'It is a warning message generated by our hosting service for security purposes.')
;

INSERT INTO tbl_textos (id_seccion, paginaPadre, identificacion, texto ) VALUES 
(39, 'pagos', 'Concept', 'pm1|pm2|pm3|pm4|pm5|pm6|pm7|pm8|pm9|pm10'),
(39, 'pagos', 'Description', 'February payment|Payment month March|Payment month April|Payment month May|June payment|Payment month July|Payment month August|Payment month September|Payment month October|Payment month November'),
(39, 'pagos', 'info financiera', '<p class=\"tx-red\"><b> <span class=\"tx-green\"> * Enter payment reference.</span> (* 5% increase in pension if you pay after the 10th)</b></p><p class=\"tx-primary-blue\"><b>NOTE:</b> The pension amount must be paid starting in February 2024 with the new costs issued by the Ministry of Education. <b>From February 1st, the cost of registration will have an additional 10% surcharge for late registration.</b> The concept of payment <b>pp (first payment)</b> It includes the tuition fee plus other periodic charges <b>(includes policy)</b> plus pension for the first month.</p>'),
(39, 'pagos', 'titulos pagos', 'Payment reference information|Data for manual value'),
(39, 'pagos', 'titulo pagos', 'Payment reference'),
(39, 'pagos', '9397454', 'Student identification number'),
(39, 'pagos', '2025', 'Year'),
(39, 'pagos', 'ocp', 'Description of the payment concept|<b>ocp</b> other periodic charges|<b>pm6</b> pension month 6|<b>m</b> enrollment|<b>p</b> policy|<b>dg</b> degree rights|<b>dgv</b> virtual degree rights|<b>pp</b> first payment|<b>mocp</b> tuition and other periodic charges')
;

INSERT INTO tbl_textos (id_seccion, paginaPadre, identificacion, texto ) VALUES 
(38, 'presaberes', 'paso', 'STEP 1'),
(38, 'presaberes', 'paso_indicacion', 'Student Information'),
(38, 'presaberes', 'paso_descripcion', 'Student ID number (without periods)'),
(38, 'presaberes', 'indicacion', 'The purpose of this assessment is to help you identify gaps in your prior knowledge or pre-existing concepts, which you should research and delve deeper into in order to develop the activities for each thought.'),
(38, 'presaberes', 'indicacion', 'At the end of the evaluation you will find a <strong>summary of the results and a suggested roadmap,</strong> This will help you turn your weaknesses into strengths and integrate them into the knowledge required for this degree.'),
(38, 'presaberes', 'indicacion', '<strong>Each question has only one attempt,</strong> but you can pause the assessment and log back in to finish it.'),
(46, 'presaberes_principal', 'indicacion', 'You will find questions about various thoughts and concepts.'),
(46, 'presaberes_principal', 'indicacion', 'All questions are related to content and topics <strong>that are necessary to know</strong> so that you can complete all the degree activities <strong>_grado*</strong>.'),
(46, 'presaberes_principal', 'titulo', 'Welcome to the pre-knowledge assessment'),
(47, 'newsletter', '', 'Educational publications and digital reflections'),
(47, 'newsletter', '', 'Institutional news and updates'),
(47, 'newsletter', '', 'Events, experiences and celebrations'),
(47, 'newsletter', '', 'Recommendations and useful tools'),
(47, 'newsletter', '', 'Add this email to your contacts so you don´t miss any posts.'),
(47, 'newsletter', '', 'You are part of an ecosystem where education resonates with you.<br><strong>You are UNICAB.</strong>'),
(47, 'newsletter', '', 'unicab.org'),
(47, 'newsletter', '', 'Cancel your subscription by doing <a href="?" style="color:rgb(46, 136, 255);">Click here.</a>'),
(47, 'newsletter', '', 'Thank you for subscribing to the UNICAB Connected blog!')
;

INSERT INTO tbl_textos (id_seccion, paginaPadre, identificacion, texto ) VALUES 
(38, 'presaberes', 'indicacion', 'The evaluation consists of <strong><label id="lblct_preg"></label> questions</strong> (or less) not quantifiable and <strong>there is no time limit.</strong>'),
(46, 'presaberes_principal', 'indicacion', 'Once again, we remind you that upon completion of the evaluation, you will find a <strong>summary of the results and a suggested roadmap, </strong>this will help you turn your weaknesses into strengths and integrate them into the knowledge required for this degree.')
;

INSERT INTO tbl_textos (id_seccion, paginaPadre, identificacion, texto ) VALUES 
(32, 'blog', 'verBlogs', 'Results of: '),
(32, 'blog', 'categoriaSeleccionada', 'News related to category: ')
;

