DROP TABLE IF EXISTS tbl_textos;

CREATE TABLE tbl_textos (
  id int(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  id_seccion int(11) NOT NULL,
  paginaPadre varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_spanish_ci NOT NULL,
  identificacion varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_spanish_ci NULL,
  texto mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_spanish_ci NOT NULL,
  INDEX fk_tbl_textos_tbl_secciones (id_seccion),
  CONSTRAINT fk_tbl_textos_tbl_secciones FOREIGN KEY (id_seccion) REFERENCES tbl_secciones (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_spanish_ci;

INSERT INTO tbl_textos (id_seccion, paginaPadre, identificacion, texto ) VALUES 
(21, 'historia', 'Fundación', 'UNICAB Corporación Educativa fue creada en la ciudad de Sogamoso mediante la Resolución No. 0194 del 18 de julio de 2001, emitida por la Gobernación de Boyacá. Desde su inicio, se estableció como una institución sin ánimo de lucro, con una filosofía de vida orientada a ofrecer el derecho-servicio educativo de manera innovadora y acorde a las necesidades de quienes participan en sus procesos, fomentando el intercambio de saberes y fortaleciendo el liderazgo de sus participantes. <br> <br> Desde su creación y hasta el año 2007, UNICAB Corporación Educativa desarrolló diversos servicios:' ),
(21, 'historia', '2002-2003', '<b>Con la Cámara de Comercio de Sogamoso:</b> Se llevaron a cabo procesos de formación, capacitación y empoderamiento de comerciantes en Sogamoso y en ocho municipios de la Provincia de Sugamuxi, a través de estrategias enfocadas en mercadeo, ventas y atención al cliente, entre otros. <br> <br> <b>Proyecto “Recuperación del Tejido Social de la Cadena Productiva del Carbón del Altiplano Cundiboyacense”:</b> Este proyecto, liderado por el Programa de las Naciones Unidas para el Desarrollo (PNUD), se implementó en 13 municipios productores de carbón en Boyacá. Se realizaron procesos de formación, sensibilización, concientización y capacitación dirigidos a trabajadores mineros, sus familias y comunidades.' ),
(21, 'historia', '2004-2007', '<b>Con el Instituto Colombiano de Bienestar Familiar (ICBF) y municipios de las provincias de Sugamuxi y Tundama:</b> En Sugamuxi: Sogamoso, Duitama, Paipa, Iza, Monguí, Gámeza, Mongua, Aquitania, Tota, Cuítiva, Corrales. En Tundama: Paipa, Duitama, Sogamoso, Corrales, Nobsa. Se desarrolló el <b>programa El Educador Familiar.</b> <br> <br> <b>Programa Atención a Población Rural Dispersa y El Educador Familiar:</b> Cofinanciado por el ICBF y 10 municipios de las provincias de Tundama y Sugamuxi, este programa atendió a comunidades rurales y poblaciones con necesidades educativas específicas. <br> <br> En 2007, surgió la necesidad de atender a personas con condiciones socioeconómicas especiales, como deportistas de alto rendimiento, artistas, familias en constante movilidad global, y campesinos que no podían acceder a la educación presencial.' ),
(21, 'historia', '2007-2008', 'Para responder a esta necesidad, se solicitó a la Secretaría de Educación de Sogamoso una licencia de funcionamiento provisional para prestar servicios educativos mediante TIC. Así nació el <b>proyecto del Colegio Virtual UNICAB </b>(www.unicab.org), autorizado por la Resolución No. 061 del 15 de diciembre de 2007. <br> <br> Desde 2008 hasta la fecha, el Colegio Virtual UNICAB ha graduado a 655 estudiantes de grado 11 y ha atendido a más de 5,000 estudiantes entre deportistas, artistas, niños, jóvenes y adultos. Este modelo ha permitido alcanzar resultados académicos sobresalientes, fomentando habilidades y motivando a los estudiantes a lograr sus metas. Muchos de ellos han obtenido becas en universidades nacionales e internacionales.' ),
(23, 'historia', 'giu', 'Es un cuerpo colegiado de investigación conformado por un grupo de maestros y asesores externos, cuyo objetivo es adelantar desarrollos científicos, tecnológicos, pedagógicos y estrategias complementarias del modelo pedagógico UNICAB Ecosistema. Este grupo gestiona proyectos y propuestas de investigación coherentes, orientados a consolidar componentes cognitivos, propedéuticos, estratégicos, metodológicos y sinérgicos para desarrollar contenidos, secuencias y métodos de aprendizaje. Todo esto se aplica en la educación virtual de forma disruptiva e innovadora dentro de un entorno cibernético, formulando y respondiendo con rigor investigativo a uno o varios problemas del entorno. Además, proporciona soluciones y medidas correctivas mediante planes estratégicos de mediano y largo plazo, con el fin de generar conocimientos concretos sobre las temáticas abordadas.' ),
(23, 'historia', 'creativo', 'Está conformado por un selecto grupo de docentes de la institución y asesores externos, quienes, de manera libre y voluntaria, aportan su intelecto y creatividad en beneficio del desarrollo instruccional, visual, corporativo, pedagógico y publicitario. Este equipo se encarga de revisar y hacer seguimiento al material didáctico-pedagógico producido por los maestros mediadores antes de que sea publicado en las plataformas tecnológicas y canales de comunicación. También contribuye al apoyo en la gestión académica, las proyecciones empresariales, eventos interinstitucionales y trabajos publicitarios requeridos.' ),
(23, 'historia', 'sistemas', 'Está integrado por docentes de la institución, ingenieros de sistemas externos y partners, quienes, de manera libre y voluntaria, contribuyen al desarrollo holístico e informático. Este equipo organiza y mantiene funcionales los recursos de hardware necesarios para la ejecución del software, buscando siempre la mayor rapidez y calidad en el manejo de la información institucional. Coordina acciones con las diferentes dependencias y usuarios del sistema para garantizar una excelente calidad en los procesos informáticos del colegio. Además, realiza labores de actualización, soporte y mantenimiento técnico o tecnológico, siguiendo las normas y procedimientos vigentes. Proporciona soporte técnico en hardware y software, capacita a usuarios en la utilización de programas, instala y actualiza aplicativos necesarios para las plataformas y efectúa controles periódicos. Asimismo, apoya en la comprensión y manejo de las tecnologías implementadas, supervisando su aplicación y funcionamiento.' ),
(23, 'historia', 'corrección', 'Este equipo se encarga de revisar los contenidos generados por los maestros en la plataforma, asegurando la calidad y corrección de los mismos. Recibe acceso a los contenidos por parte del líder del pensamiento y brinda retroalimentación a través de informes que incluyen observaciones y sugerencias para mejoras. También revisa documentos antes de su publicación o envío mediante los diferentes medios de comunicación. Al igual que el equipo creativo, puede utilizar un formato tipo lista de chequeo para garantizar un análisis estructurado y eficiente.' ),
(23, 'historia', 'maestros', 'Este grupo está constituido por todo el personal docente con carga académica en el Colegio Virtual UNICAB, quienes además tienen asignada la dirección de grado. Este año se implementó un formato denominado Informe General de Dirección de Grado, que documenta tanto la carga académica como las actividades relacionadas con la dirección de grado. Aunque confiamos plenamente en la labor del personal, la experiencia ha demostrado la importancia de dejar evidencia para respaldar las acciones realizadas. <br><br> El grupo también evalúa el nivel de participación de los estudiantes en el pensamiento, describiendo el desempeño de cada uno con el propósito de establecer criterios objetivos de valoración. Esto permite aplicar estrategias preventivas, correctivas y productivas para mejorar el desempeño y garantizar la inclusión o promoción de los estudiantes.' ),

(29, 'principiosYValores', 'Compromiso', 'El colegio está comprometido en desarrollar a través de la mejora continua y el esfuerzo de un equipo de trabajadores que estudian, investigan, atienden y prestan los mejores servicios educativos a la comunidad, que garantizan la calidad y la excelencia de los aprendizajes en los proyectos de vida de estudiantes que han descubierto habilidades y destrezas, y que las potencializan con autonomía, libertad e identidad motivados por el deseo de cumplir con sus expectativas, el logro de las metas y objetivos de la institución, para que transformen con libertad una verdadera educación que desarrolle su personalidad autónomamente, apropiando el conocimiento en su vida práctica como lo planteaba John Dewey y como resultado el beneficio individual, familiar y comunitario.' ),
(29, 'principiosYValores', 'Honestidad', 'Actuar bajo la normatividad vigente con responsabilidad y ética en todos los aspectos relacionados con el desarrollo e interacción de las actividades de la institución con la sociedad. Ser transparentes en todo, y asegurar que cada una de las políticas adoptadas dentro del colegio, así como los compromisos adquiridos, sean sustentados a través de procesos definidos, integrados y ejecutados en las formas mismas que los estándares de calidad propuestos, a través de una estructura definida del quehacer institucional y su impacto en la sociedad.' ),
(29, 'principiosYValores', 'Libertad', 'Es la respuesta al silogismo ideológico de lo que se espera con respecto a lo que se es, nuestros estudiantes surten un proceso de acompañamiento que les permite identificarse y auto definirse para ser libres, para que empoderados se sientan eficientes a la hora de tomar decisiones; por lo que buscamos y privilegiamos siempre la verdad sin restricciones, para producir el conocimiento y el progreso de la sociedad con conciencia sobre sus intereses, derechos, deberes y responsabilidades políticas con un alto sentido de responsabilidad colectiva.' ),
(29, 'principiosYValores', 'Equidad', 'La dimensión pedagógica de la equidad en educación, fundamenta su escala estratégica para hacer frente a las desigualdades que subsisten pese a las políticas de ampliación de oportunidades registradas a escala mundial. Sustentamos un concepto de equidad integral, que recoge los postulados y fines propios de la educación en Colombia, con el de inclusión social para la participación y el empoderamiento, con asentamiento en las pedagogías críticas, de la capacidad y la educación centrada en el estudiante, que engloba procesos educativos inclusivos y dialógicos para fortalecer la agencia de los estudiantes no tradicionales en un modelo pedagógico virtual, tanto para aprender como para revertir las exclusiones educativas y sociales acumuladas. Esta dimensión es clave para optimizar las estrategias de ampliación de accesibilidad y cobertura que tan ardua alusión hace la ley general de educación frente a los fracasos que experimenta el estudiantado tradicional. Ello se evidencia en el análisis de prácticas innovadoras presenta este proyecto educativo.' ),
(29, 'principiosYValores', 'Responsabilidad', 'Surge como la alternativa para suplir una necesidad a los intereses de aquellos que siendo diferentes solicitan ser acogidos y acompañados en sus procesos y actividades extracurriculares en las artes, el deporte, la ciencia, la tecnología, y la investigación que desarrolla el mundo contemporáneo, en el que curiosa y comprometidamente quieren desenvolverse, pero que por convencionalismos formativos no se les permite espacios para cumplir sueños e inquietudes que los hacen diferentes. UNICAB encuentra ese esquema y se une al deseo de aquellos que por su proyecto de vida quieren transcender a otros escenarios, acompañados por un equipo de maestros comprometidos que orientan los procesos enseñanza aprendizaje con sensibilidad y consciencia y los tornan flexibles a través de la virtualidad humanizando el proceso, a través de un modelo pedagógico eco sistémico e investigativo.' ),

(30, 'cartiHome', 'Misión', '<b>CARTI EXPLORA</b> es el Centro de Alto Rendimiento para el Talento y la inteligencia, innovador y pertinente, constituido como un centro altamente humanista, para la formación del talento para niños, niñas y jóvenes, en donde confluyen la educación formal, la cultura y el deporte, con la redefinición del aprendizaje para que los seres humanos desarrollen sus destrezas, habilidades y talentos, resuelvan sus problemas en equidad y amplíen sus oportunidades en búsqueda de la felicidad.' ),
(30, 'cartiHome', 'Visión', '<b>CARTI EXPLORA</b> en el año 2030 será reconocido a nivel regional y nacional como un colegio constituido en un centro de formación de alto rendimiento, modelo en la redefinición de los paradigmas de la educación, lider en la formación del talento y la educación virtual, que consistentemente aplica enfoques innovadores, inspirando el fortalecimiento de disciplinas deportivas, culturales, científicas y sociales, fomentando habilidades para el siglo XXI y celebrando la creatividad, la investigación y el esfuerzo para darle sentida de vida a sus estudiantes.' ),
(30, 'cartiHome', 'Principios Insititucionales', '<b>CARTI EXPLORA</b>, propende por la formación Integral de sus estudiantes en un contexto totalmente innovador, a través de una estructura fisica, digital, curricular y de formación para que el resultado de aprendizaje de sus estudiantes sea autónomo y consciente en un proceso de aprendizaje definido con una metodología de enseñanza flexible, dinámica, pertinente basados en principlos éticos para que junto con el desarrollo de capacidades, habilidades y destrezas en áreas específicas, puedan tener un excelente desempeño en su' ),
(30, 'cartiHome', 'Compromiso', 'El colegio está comprometido en desarrollar a través de la mejora continua y el esfuerzo de un equipo de trabajadores que estudian, investigan, atienden y prestan los mejores servicios educativos a la comunidad, que garantizan la calidad y la excelencia de los aprendizajes en los proyectos de vida de estudiantes que han descubierto habilidades y destrezas, y que las potencializan con autonomia libertad e identidad motivados por el deseo de cumplir con sus expectativas, el logro de las metas y objetivos de la institución, para que transformen con libertad una verdadera educación que desarrolle su personalidad autónomamente, apropiando el conocimiento en su vida práctica como lo planteaba John Dewey y como resultado el beneficio individual, familiar y comunitario.' ),
(30, 'cartiHome', 'Ética', 'Actuar bajo la normatividad vigente con responsabilidad y honestidad en todos los aspectos relacionados con el desarrollo e interacción de las actividades de la institución con la sociedad. Ser transparentes en todo, y asegurar que cada una de las políticas adoptadas dentro del colegio, así como los compromisos adquiridos, sean sustentados a través de procesos definidos integrados y ejecutados en las formas mismas que los estándares de calidad propuestos, a través de una estructura definida del quehacer institucional y su impacto en la sociedad.' ),
(30, 'cartiHome', 'Libertad', 'Es la respuesta al silogismo ideológico de lo que se espera con respecto a lo que se es, nuestros estudiantes surten un proceso de acompañamiento que les permite identificarse y auto definirse para ser libres, para que empoderados se sientan eficientes a la hora de tomar decisiones; por lo que buscamos y privilegiamos siempre la verdad sin restricciones, para producir el conocimiento y el progreso de la sociedad con conciencia sobre sus intereses, derechos, deberes y responsabilidades políticas con un alto sentido de responsabilidad colectiva.' ),
(30, 'cartiHome', 'Equidad', 'La dimensión pedagógica de la equidad en educación, fundamenta su escala estratégica para hacer frente a las desigualdades que subsisten pese a las políticas de ampliación de oportunidades registradas a escala mundial. Sustentamos un concepto de equidad integral, que recoge los postulados y fines propios de la educación en Colombia, con el de inclusión social para la participación y el empoderamiento, con asentamiento en las pedagogías críticas, de la capacidad y la educación centrada en el estudiante, que engloba procesos educativos inclusivos y dialógicos para fortalecer la agencia de los estudiantes no tradicionales en un modelo pedagógico disruptivo, tanto para aprender como para revertir las exclusiones educativas y sociales acumuladas. Esta dimensión es clave para optimizar las estrategias de ampliación de accesibilidad y cobertura que tan ardua alusión hace la ley general de educación frentela los fracasos que experimenta el estudiantado tradicional. Ello se evidencia en el análisis de prácticas innovadoras presentes en este proyecto educativo.' ),
(30, 'cartiHome', 'Responsabilidad', 'Surge como la alternativa para suplir una necesidad a los intereses de aquellos que siendo diferentes solicitan ser acogidos y acompañados en sus procesos y actividades pedagógicas para fortalecer los talentos asociados a las artes,el deporte, la ciencia, la tecnología, y la investigación que desarrolla el mundo contemporáneo, en el que curiosa y comprometidamente quieren desenvolverse, pero que por convencionalismos formativos no se les permite espacios para cumplir sueños e inquietudes que los hacen diferentes.<br><br><b>CARTI EXPLORA</b> encuentra ese esquema y se une al deseo de aquellos que por su proyecto de vida quieren trascender a otros escenarios, acompañados por un equipo de maestros comprometidos que orientan los procesos enseñanza aprendizaje con sensibilidad y consciencia y los tornan flexiblesia través de experienciaside exploración y profundización del talento, humanizando el proceso, a través de un modelo pedagógico eco sistémico e investigativo.'),
(30, 'cartiHome', 'Pertinencia', 'Habrá una constante autoevaluación de las potencialidades del colegio con respecto a sus estrategias y metodologías, en los diferentes ámbitos como el intelectual, el socio afectivo y el práxico los que involucran la calidad de sus relaciones, el testimonio de estudiantes y futuros egresados, la participación de las familias, para cultivar una actitud crítica de cara a la sociedad contemporánea. Eso va a propiciar un continuo rediseño fomentado en la democracia y la participación, favoreciendo. el trabajo conjunto de las familias, los maestros, los alumnos y del entorno, por lo que CARTI EXPLORA, en cabeza de sus directivos consolidará la calidad e idoneidad educativa mediante la reflexión pedagógica continua, la apropiación de metodologías y técnicas didácticas más eficaces, la cualificación permanente del talento humano. para hacer orgánico nuestro modelo pedagógico.'),

(31, 'blog', 'linkBusqueda', 'Celebración de Logros'),
(31, 'blog', 'linkBusqueda', 'Proyectos y experiencias'),
(31, 'blog', 'linkBusqueda', 'Investigación GIU'),
(31, 'blog', 'barraBusqueda', 'Buscar'),

(34, 'entrevista', 'Paso 1.', 'Ingresa los siguientes datos para iniciar el proceso de matrícula en nuestro colegio UNICAB Virtual.'),
(34, 'entrevista', 'Paso 2.', 'Datos complementarios del estudiante.'),
(34, 'entrevista', 'Paso 3.', 'Datos complementarios del acudiente.');

INSERT INTO tbl_textos (id_seccion, paginaPadre, identificacion, texto ) VALUES 
(36, 'admisiones', 'Texto1', '¡EL REGISTRO SE TERMINÓ CON ÉXITO PARA EL DOCUMENTO: '),
(36, 'admisiones', 'Texto2', 'A la dirección de correo del acudiente se le enviará:'),
(36, 'admisiones', 'Texto3', 'Un link para contestar la evaluación de admisión que se debe presentar al momento de la entrevista.'),
(36, 'admisiones', 'Texto4', 'Un link con el día y hora en la que se programó la entrevista.'),
(36, 'admisiones', 'Texto5', 'Es probable que cuando le llegue el correo le aparezca una imagen como esta:'),
(36, 'admisiones', 'Texto6', 'No haga clic en ninguna de las opciones de la imagen.'),
(36, 'admisiones', 'Texto7', 'Es un mensaje de advertencia que genera por seguridad nuestro hosting.')
;

INSERT INTO tbl_textos (id_seccion, paginaPadre, identificacion, texto ) VALUES 
(39, 'pagos', 'Concepto', 'pm1|pm2|pm3|pm4|pm5|pm6|pm7|pm8|pm9|pm10'),
(39, 'pagos', 'Descripción', 'Pago mes febrero|Pago mes marzo|Pago mes abril|Pago mes mayo|Pago mes junio|Pago mes julio|Pago mes agosto|Pago mes septiembre|Pago mes octubre|Pago mes noviembre'),
(39, 'pagos', 'info financiera', '<p class=\"tx-red\"><b> <span class=\"tx-green\"> * Ingrese referencia de pago.</span> (* Incremento de 5% en pensión si paga después del día 10)</b></p><p class=\"tx-primary-blue\"><b>NOTA:</b> El valor de la pensión se debe pagar a partir de febrero del año 2024 con los nuevos costos emitidos por la Secretaría de Educación. <b>A partir del 1 de febrero el costo por concepto de matrícula tendrá un recargo adicional del 10% por extemporaneidad.</b> El concepto de pago <b>pp (primer pago)</b> incluye el valor de la matrícula más otros cobros periódicos <b>(incluye póliza)</b> más pensión primer mes.</p>'),
(39, 'pagos', 'titulos pagos', 'Datos para referencia de pago|Datos para valor manual'),
(39, 'pagos', 'titulo pagos', 'Referencia de pago'),
(39, 'pagos', '9397454', 'Número de identificación del estudiante'),
(39, 'pagos', '2025', 'Año'),
(39, 'pagos', 'ocp', 'Descripción del concepto de pago|<b>ocp</b> otros cobros periodicos|<b>pm6</b> pensión mes 6|<b>m</b> matrícula|<b>p</b> póliza|<b>dg</b> derechos de grado|<b>dgv</b> derechos de grado virtual|<b>pp</b> primer pago|<b>mocp</b> matrícula y otros cobros periódicos')
;

INSERT INTO tbl_textos (id_seccion, paginaPadre, identificacion, texto ) VALUES 
(38, 'presaberes', 'paso', 'PASO1'),
(38, 'presaberes', 'paso_indicacion', 'Informacion del estudiante'),
(38, 'presaberes', 'paso_descripcion', 'Numero de documento de identidad del estudiante (sin puntos)'),
(38, 'presaberes', 'indicacion', 'El propósito de esta evaluación es ayudarte a identificar las falencias en los conceptos previos o presaberes, en los cuales debes investigar y profundizar para desarrollar las actividades de cada pensamiento.'),
(38, 'presaberes', 'indicacion', 'Al concluir la evaluación encontrarás un <strong>resumen del resultado y una hoja de ruta sugerida,</strong> esta servirá para convertir tus falencias en fortalezas e integrarlas a los conocimientos requeridos para este grado.'),
(38, 'presaberes', 'indicacion', '<strong>Cada pregunta tiene un solo intento,</strong> pero puedes pausar la evaluación y volver a ingresar para finalizarla.'),
(46, 'presaberes_principal', 'indicacion', 'Vas a encontrar preguntas de varios pensamientos y varios conceptos.'),
(46, 'presaberes_principal', 'indicacion', 'Todas las preguntas están relacionadas con contenidos y temas <strong>que son necesarios conocer</strong> para que puedas desarrollar todas las actividades de grado <strong>_grado*</strong>.'),
(46, 'presaberes_principal', 'titulo', 'Bienvenido a la evaluación de presaberes'),
(47, 'newsletter', '', 'Publicaciones educativas y reflexiones digitales'),
(47, 'newsletter', '', 'Noticias y novedades institucionales'),
(47, 'newsletter', '', 'Eventos, experiencias y celebraciones'),
(47, 'newsletter', '', 'Recomendaciones y herramientas útiles'),
(47, 'newsletter', '', 'Agrega este correo a tus contactos para no perderte ninguna entrada.'),
(47, 'newsletter', '', 'Eres parte de un ecosistema donde la educación vibra contigo.<br><strong>Eres UNICAB.</strong>'),
(47, 'newsletter', '', 'unicab.org'),
(47, 'newsletter', '', 'Cancela tu suscripcion haciendo <a href="?" style="color:rgb(46, 136, 255);">click aqui.</a>'),
(47, 'newsletter', '', '¡Gracias por suscribirte al blog Conectados de UNICAB!')
;

INSERT INTO tbl_textos (id_seccion, paginaPadre, identificacion, texto ) VALUES 
(38, 'presaberes', 'indicacion', 'La evaluación consta de <strong><label id="lblct_preg"></label> preguntas</strong> (o menos) no calificables cuantitativamente y <strong>no hay límite de tiempo.</strong>'),
(46, 'presaberes_principal', 'indicacion', 'Una vez más te recordamos que al concluir la evaluación, encontraras un <strong>resumen del resultado y una hoja de ruta sugerida, </strong>para esta servirá para convertir tus falencias en fortalezas e integrarlas a los conocimientos requeridos para este grado.')
;

INSERT INTO tbl_textos (id_seccion, paginaPadre, identificacion, texto ) VALUES 
(32, 'blog', 'verBlogs', 'Resultados de: '),
(32, 'blog', 'categoriaSeleccionada', 'Noticias relacionadas a categoria: ')
;

